apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:fNP2P/WeBnPTNu+LR17A2j4iDLPMNZ3uzmMNGJo38Wo9aprP3o0Jog==,iv:Pw6kE/R7YOiU1fbTol1u/QR3EUFQFVpZxNHOclI3SyM=,tag:4OjsdpII7bpqUSPZijIsqA==,type:str]
sops:
  age:
    - recipient: age1g2g9f7njaxqdtggvupuplfmcv6n2pugcsfcayd4zm8qunppsrq3qm6fpgf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSdy8vekJ2Q0hpS1ZYc3Nq
        MXBVL2lSSld6T2tJYUhpc0ZXQVNwSi9YeHdJCmMrcENZMElvY3Q5WE9SNzZWQkky
        ZXJFV2xYaDE3am42MUs3RmNBL0NMbzgKLS0tIDFReTNmaTBEVlNCZEZsaWozM1Jl
        ODFHOEJpYXM0Z0xUQW9NVjZja2lXY28KoClv9pn6zuNEwfxD6El+gqLXZCh3X/36
        +uTT5cnf78NkLbOR4B1ypG6Vq1y6ozw1I1eqX4z80XecWTHsIpDNzg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-18T17:13:47Z"
  mac: ENC[AES256_GCM,data:4QcxCOUlvJLDfFgU/MmjRKlDX0mcvRmsG3P14lX44ZHvS3IHJFDxz+wiZXymV5lPkQiXFdXe0qyves+VDAIcuSfZnFltV3p9WZn+bme6XwyBsr/SgfgMbDFEgnL40RNVGcViE5XrCeJLzWx+xbv52Md3nqU4fs4uNXDkBVZ1vyQ=,iv:3dhySF84r/tQQXoiOQmy9fCbd+e1OfIKa7yH2ztCt60=,tag:HnJ3+ttRlNQqDyrwbFf/WA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
