apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:m2SfAp9xSu/EYBJ0+w==,iv:t9K2Arnq3HOufsnngy6/nx3K18WeNu/N/QOdVuZWvIs=,tag:S6sA6lsTLXjouta1sq5H/g==,type:str]
sops:
  age:
    - recipient: age1g2g9f7njaxqdtggvupuplfmcv6n2pugcsfcayd4zm8qunppsrq3qm6fpgf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZMnhUbXdyWVBCYjRGUWNx
        V3ptZ1ZrZXRDQkdGSllLbCtqTGl0Y2NXMVNBCmZ5TEJJYkcxOEtUM0NEVWdpcUgr
        YXZteEo0TnFmN0RaL04rcnpVQXZpak0KLS0tIEVCSklPYUlVL2pucklBN0lEMSt4
        eEtTbklOeEtTWjBaVXZVQUhhUitSK2MKPfqxQPCmxFSi9zHq+VMOohQ4qkgxcShW
        jcsa3Bw46+wOmWqQQkTurGJXzY/DnK8JzEshTufxABu/9lzTGBT11g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-18T17:13:46Z"
  mac: ENC[AES256_GCM,data:GbujiDpGbPNU/pJqdmG0psUNKSx7IfaAcxSi9nComWwuYw/mFd6BoxQEqZ/FfLjmZFKQ+2ISdrPQr1LmcH0yLMUuLz+i6Ac4cYPY6TT0I2QpOmssc8yfR8p65e8+vwLTzzHj0V0Oq5lziMA9tgH384Z2nK0UG9fy4WqvFwYm9g4=,iv:jM7TTfU7Zc+p5TK2wcO2UCFP4etuIK1/wnJrnTGr2ts=,tag:0b+SZCjbSSR0z1xnNHHspQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
