apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:y/4pxC0IO+0R+/9Lw1Pa3rGnsNu3/B1sMtCimbRM5V0=,iv:0Fl1wV4Qu9vaerlzXzmedcZsTzTPDDphhtaPeFdeKCA=,tag:Mm67bgb0B1TX3RlkvnK9WA==,type:str]
sops:
  age:
    - recipient: age1g2g9f7njaxqdtggvupuplfmcv6n2pugcsfcayd4zm8qunppsrq3qm6fpgf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5dmRzbk9yZEp1M1hDbjIy
        VlB0bnFneG5RTE4xd1VUb243Y0MvK1FGSXdjCmRueUVLVFNFaTVwaDJ6TlFkNjEz
        OTI4MzU1NzRCQ0JJTjJ3bXovZ2xqNXcKLS0tIGFpZm9ORGdyYnFsZFUxWE4rUHFu
        UDJjWDFJY3FTb2NoZVhWbzZjSWlsdDQKsLsPNOgYrZObhAkjv+ku6A7+qIwqrOSy
        iVkczBVTUwBbzJD6e5czSRtD2XZMD+pu5pAlpNkDJV7OfJ5Q4qiPHQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-18T17:13:46Z"
  mac: ENC[AES256_GCM,data:942FScirP1B+78lWPF/ndz8mz74cImn0wPBfiTGmLWfoVh1MYuunKDsfomMUq0rDjqu4YOpRpgOx0bV7IpAic23C3Uid53xi2x/0F0cxAC7i81rkaUT7Yq2F5hYieNF5Obf+OFWmpoIIcGO51yHWqi9P7UUzhwFpZHV+987oNlk=,iv:nHRPL03s+Nm/HWEGAa70SElKoK5nvo8fy0Tr0afV1M8=,tag:4TWLwbY9nvLj4plE9u3J5A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
