apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:I+coeGGGXBUKZuViZVPIxjFSFmx9t/aEbVP+BunIwGyfQDff/Ggsl7gH9xPHpRoKWz+iCkVVUqoKP+Hwdi4in2hc9C2LkaNEi2j0XUChb2bLvo9UTO3GczySzs++mwFr1o/nBE3vKvaHjkoLpn9ioCngDby5S4QnfJKzEhC/SclnO4SJ/4JQQ87HamDGtZK5jOcyydIePSfLr8js1A7O8RH6zzxNVvPbclEpM87gKaUCX0Fa,iv:BoiLyklTMzD2L74Wpm9Uqzt93LjV7J4cIEHVXOXiJck=,tag:uOJYh3VQ1QDCt86tuQ15nQ==,type:str]
sops:
  age:
    - recipient: age1g2g9f7njaxqdtggvupuplfmcv6n2pugcsfcayd4zm8qunppsrq3qm6fpgf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMDZqUWc1TEZTWFZqc1pC
        S1Iyb1dOWmVtaURTOTNQMWgwcXB2T2Mwd25rCjNQc0x5L3Z3WmRMVnFLYUhlL3FD
        UVVHK0xaNThpTkZFckRJZnJkWXJPcG8KLS0tIHl3UDFTalVRZUcrMUlPd0RrQmdH
        Zm5NUXc5aXVGQnZranZIU1JvbldLQ0kKUD3x1mUEhKhShDuOiAuXMxual7asyRaV
        BPnJAYyjIB04207rLl5Sl3lMgmSalvLenCcL3eOXv/54psmvBLMJ3w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-18T17:13:47Z"
  mac: ENC[AES256_GCM,data:zaMCgtGYe2DfNrvuFMWMsgkq74ViBjkzng5JYDJvGw7nBgyK+eoV97tOW+fo0qRUKqDCDh9eZNm6prkVFvIif3NaDpYv19Ome9RaCSObvrXIEKpRF+Q57JsF6qWEa0KTNNW0cFIYnLiOdnGtBuTuSL442BL47emw0gsk+xs5Mlg=,iv:MedYwZd9ULpCoT2T1eUWt27/ZgIZ/7BEn6ocz3VcIKY=,tag:8HioybXPOWaJD0w9JLiRVA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
