apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:azE53Hw4pcOQ+6c9J/g2poIsTJMc9Muk8Zw4ylVl3ApjQ2DB+gPVGQ==,iv:EnnEsLdFDCGuWaq1TFIcC4NRNYSiAERJne+eKRNKfVk=,tag:MUW6GhCDH/swgvzhwIhq4Q==,type:str]
sops:
  age:
    - recipient: age1g2g9f7njaxqdtggvupuplfmcv6n2pugcsfcayd4zm8qunppsrq3qm6fpgf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvKzhla1UyUVRXaVRqT3Vs
        c0lEaS9lUEN3UTIrcFh4RzMzeUY0NkJJWTA0Cmx4Z2pYWEQ1N2p4VEtYSUJTRlFQ
        VDFnT3B3RlFYR0FkWWxldFh3d09PTVEKLS0tIG00cDIweVM2TnFIYkMwZFhhd3BX
        U21kU0F1ZVFTeHd5TkVDZ01VbjAvaG8KAIeIdXXLUIq1YGQaNkKU8x+c8hmdz+YL
        0iVCXWlRp5jR5fSsZN43OR+5CB/NE0Cf25byxHp+7ngZSJ6ySxtQ1w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-18T17:13:47Z"
  mac: ENC[AES256_GCM,data:BN0obZjd90VL46bBchtV0ObJqrVJExfXDDIEXoI2fSkDF1m8s964yNQJ2teKatqIXnu2UWihBWMMNSaGhhbLZYgF6sZiXCshHwbU76iXMWdXjR1xwzFBGQXTHdHy1GHb26+NvN1GNOvxIQrSe2HxTST4hzo+C/TffXOuQ1spKCM=,iv:NR4fbs2br7vgf2hI0ZJ6y8MV4TGle26w1oF1pMyLJGI=,tag:WqsvH1sCXs0NUV8XQ8l2kw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
